### ISSUE TITLE
WWI-SalesOrders.pbix - Invalid object name 'Website.SalesOrders'.

### ISSUE THREAD

**Issue by Pietervanhove** [Microsoft/sql-server-samples#391]
Hi Jos,

When I open the WWI-SalesOrders.pbix file and connect to my WideWorldImporters database (fresh copy I've just downloaded), I get an error message:

Error Message:
Invalid object name 'Website.SalesOrders'.. The exception was raised by the IDbCommand interface.

When I check the sys.objects I can't find the object. Am I missing something or is the backup file not up to date?

Best Regards
Pieter Vanhove

**Comment by jodebrui** [comment]
You need to install the sample databases from source code, because some of the views the dashboards depend on have not yet made it to the released version of the sample databases. I updated the readme for the dashboards to call this out.

**Comment by wcmchan** [comment]
HI Jobdebrui
followed your instruction "install the sample DB from source code", but seem that not work . Object not found Website.SalesOrders.  I have recreated the database using scripts under ...\samples\databases\wide-world-importers\ folder. please advise, thank you

**Comment by FatherOSam** [comment]
Message=Invalid object name 'Website.SalesOrders'
Can someone just publish the design for this view ?

**Comment by prthor** [comment]
> Hi Jos,
> 
> When I open the WWI-SalesOrders.pbix file and connect to my WideWorldImporters database (fresh copy I've just downloaded), I get an error message:
> 
> Error Message:
> Invalid object name 'Website.SalesOrders'.. The exception was raised by the IDbCommand interface.
> 
> When I check the sys.objects I can't find the object. Am I missing something or is the backup file not up to date?
> 
> Best Regards
> Pieter Vanhove

I didn't find the views too, so I created them. Let me know if it works for you guys or something needs to be changed.

I have converted the column "DeliveryLocation" (type: geography) to nvarchar, since geography type columns cannot be grouped by. Converting to nvarchar shows latitude and longitude with some extra text "POINT ( " which can be cleaned if needed.

![DataLoadSimulation_PopulateDataToCurrentDate_With_StartDate](https://user-images.githubusercontent.com/53116269/67623513-918dd700-f843-11e9-8a20-ef9074de1722.PNG)

**Comment by jwilki1** [comment]
I am getting this error as well
Microsoft SQL: Invalid object name 'Website.SalesOrders'.

How do I create this view, user parthor and https://github.com/prthor/wwi-related/tree/master/wwi/views no longer exist.  I know this is an old thread but it is still an issue in 2021.

Thank you for any assistance!

**Comment by parthor** [comment]
> I am getting this error as well
> Microsoft SQL: Invalid object name 'Website.SalesOrders'.
> 
> How do I create this view, user parthor and https://github.com/prthor/wwi-related/tree/master/wwi/views no longer exist. I know this is an old thread but it is still an issue in 2021.
> 
> Thank you for any assistance!

Hi jwilki1,

I wasn't using my repo much, so deleted it but as per  @jodebrui 's comment it might be this one (I am not sure):

https://github.com/microsoft/sql-server-samples/blob/master/samples/databases/wide-world-importers/wwi-ssdt/wwi-ssdt/WebApi/Views/SalesOrders.sql

(The schema is different)

**Comment by mvanreek** [comment]
It looks like this issue is not solved yet (24/11/2023), but to have at least some data in the report, I changed the 2 queries:

*1 Sales
SELECT SO.OrderID, OrderDate, NULL AS OrderNumber, NULL AS CustomerName, NULL AS DeliveryLocation, NULL AS SalesPerson, SUM(Quantity * UnitPrice) AS OrderPrice FROM Sales.Orders SO JOIN Sales.OrderLines SOL ON SO.OrderID=SOL.OrderID GROUP BY SO.OrderID, OrderDate

*2 LastDaySales
SELECT SO.OrderID, OrderDate, NULL AS OrderNumber, NULL AS CustomerName, NULL AS DeliveryLocation, NULL AS SalesPerson, SUM(Quantity * UnitPrice) AS OrderPrice FROM Sales.Orders SO JOIN Sales.OrderLines SOL ON SO.OrderID=SOL.OrderID WHERE OrderDate >= DATEADD(day, -1, CAST(SYSDATETIME() AS date)) GROUP BY SO.OrderID, OrderDate
